### ISSUE TITLE
App crashes if name already exists in the shared preferences

### ISSUE THREAD

**Issue by till-tomorrow** [till-tomorrow/Bahi-Khata#1]
sharedpreferences are used to store the name of the person(string) and the corresponding amount(integer). If the name already exists in the shared preferences, then the app crashes.

**Comment by panwarab** [comment]
share the code please

**Comment by till-tomorrow** [comment]
I have shared the required files..kindly check. The issue is in MainActivity,java

**Comment by till-tomorrow** [comment]
I have issues with pushing the code to github, so I'm unable to share the entire folder!!
